const assert=require('node:assert/strict');
const C=require('../core.js');
assert.equal(C.difficulty({km:2,gain:100}),'Facile');
assert.equal(C.difficulty({km:3,gain:1}),'Moyen');
assert.equal(C.difficulty({km:5,gain:100}),'Moyen');
assert.equal(C.difficulty({km:5,gain:101}),'Difficile');
assert.equal(C.flow({km:2,pedestrian:100,sidewalk:0,lights:0}),100);
assert.equal(C.flow({km:1,pedestrian:0,sidewalk:100,lights:0}),65);
assert.equal(C.flow({km:1,pedestrian:0,sidewalk:100,lights:20}),0);
assert.equal(C.distance({lat:48.85,lon:2.35},{lat:48.85,lon:2.35}),0);
assert.ok(Math.abs(C.distance({lat:0,lon:0},{lat:0,lon:1})-111.195)<.01);
assert.equal(C.time(65),'1:05');
const activity={schemaVersion:1,sport:'running',durationSeconds:720,distanceMeters:2400,startedAt:'2026-10-05T08:00:00+02:00',source:'Test',demo:true};
assert.equal(C.validateActivity(activity).durationSeconds,720);
assert.throws(()=>C.validateActivity({...activity,durationSeconds:NaN}));
assert.throws(()=>C.validateActivity({...activity,durationSeconds:0}));
assert.throws(()=>C.validateActivity({...activity,distanceMeters:'2400'}));
assert.throws(()=>C.validateActivity({...activity,startedAt:'pas une date'}));
assert.throws(()=>C.validateActivity({...activity,sport:'cycling'}));
console.log('16 assertions de calcul et validation : OK');
